### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Baltazar6** [CamTosh/OneFreeMonth#1]
Hello,
Hope you are doing well. Humble request to you.
Can you plz make a video demo on how to use your code since i am new to python.
I have already install python on ubuntu. But i am stuck at the step py app.py --help.
I got this message below. How should i proceed.
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable
usage: py [-x] [-l] [-c PRE_CMD] [-C POST_CMD] [-V] [-h] [expression]

positional arguments:
  expression     e.g. py '2 ** 32'

Options:
  -x             treat each row of stdin as x
  -l             treat list of stdin as l
  -c PRE_CMD     run code before expression
  -C POST_CMD    run code after expression
  -V, --version  version info
  -h, --help     show this help message and exit

Thnks in advance for your help and support for new users

**Comment by ghost** [comment]
I figured it out, like this: python app.py --netflix NETFLIX

**Comment by M0nster420** [comment]
I got this :/

optional arguments:
  -h, --help         show this help message and exit
  --env ENV          Select .env file
  --netflix NETFLIX  Create Netflix account
  --ocs OCS          Create Ocs account
$ --netflix NETFLIX
--netflix: command not found

**Comment by ghost** [comment]
sorry don't know what's the problem... Working on my Windows 10.

**Comment by vedantjangid** [comment]
i am getting something like this => 
Selected provider: Netflix
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bot'\OneFreeMonth\app.py", line 24, in <module>
    provider = Netflix()
  File "C:\Users\Admin\Desktop\bot'\OneFreeMonth\Netflix.py", line 13, in __init__
    self.browser = webdriver.Chrome(options=options)        
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

______________________________________________________________________________________________________

can you help

**Comment by hsratneshsci** [comment]
hi can i get some help here
